config/routes.rb
Rails.application.routes.draw do
	
  devise_for :users

  resources :posts do 
  	resources :comments
  end
  
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

 def username
 	return self.email.split('@')[0].capitalize 
 end

 has_many :posts
 has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_action :find_post 
before_action :find_comment, only: [:destroy, :edit, :update, :comment_owner]
before_action :comment_owner, only: [:destroy, :edit, :update]



def create
	@comment = @post.comments.create(params[:comment].permit(:content))
	@comment.user_id = current_user.id
	@comment.save

	if @comment.save
		redirect_to post_path(@post)
	else
		render 'new'
	end
end

def destroy
	@comment.destroy
	redirect_to post_path(@post)
end

def edit
	
end

def update
	if @comment.update(params[:comment].permit(:content))
		redirect_to post_path(@post)
	else
		render 'edit'
	end
end

private

def find_post
	@post = Post.find(params[:post_id ]) 
end

def find_comment
  @comment = @post.comments.find(params[:id]) 		
end

def comment_owner
	unless current_user.id == @comment.user_id
		flash[:notice] = "You shall not pass!"
		redirect_to @post
	end
end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :post_owner]
  before_action :authenticate_user!, except: [:show, :index]
  before_action :post_owner, only: [:destroy, :update, :edit]
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comments = Comment.where(post_id: @post).order("created_at DESC")  
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    def post_owner
  unless current_user.id == @post.user_id
    flash[:notice] = "You shall not pass!"
    redirect_to @post
  end
end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :a, :b, :c, :d, :otvet, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<% @comments.each do |comment| %>
   <p><%= comment.user.username %></p>
   <p><%= comment.content %></p>

   <% if current_user == comment.user || current_user.admin %>
  <%= link_to "Delete comment", [comment.post, comment], method: :delete %>
  <%= link_to "Edit comment", edit_post_comment_path(comment.post, comment) %>
  <% end %>
<% end %>

<%= render 'comments/form' %>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
 <%= f.text_area :content %>
 <%= f.submit %>
 <% end %>

app/views/comments/edit.html.erb
<%= form_for([@post, @comment]) do |f| %>
 <%= f.text_area :content %>
 <%= f.submit %>
 <% end %>

app/views/layouts/_alert.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Test1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/alert' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Helowww leegeza</h1>

<% if current_user %>
<%= link_to "Delete", destroy_user_session_path, method: :delete %>
<% else %>
<%= link_to "Sign_up", new_user_registration_path  %>

<%= link_to "Log_up", new_user_session_path  %>

<% end %>
<p>
<%= link_to "Post", posts_path %>
</p>	

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_area :title %>
  </div>

  <div class="field">
    <%= form.label :a %>
    <%= form.text_area :a %>
  </div>

  <div class="field">
    <%= form.label :b %>
    <%= form.text_area :b %>
  </div>

  <div class="field">
    <%= form.label :c %>
    <%= form.text_area :c %>
  </div>

  <div class="field">
    <%= form.label :d %>
    <%= form.text_area :d %>
  </div>

  <div class="field">
    <%= form.label :otvet %>
    <%= form.text_area :otvet %>
  </div>

  

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td>(<%= post.a %></td>
        <td><%= post.b %></td>
        <td><%= post.c %></td>
        <td><%= post.d %>)</td>
         <% if current_user && current_user.admin %>
        <td>(<%= post.otvet %>)</td>
        <% end %>
        <td><%= post.user.username %></td>
        <% if user_signed_in? %>
        <td><%= link_to 'Show', post %></td>
        <% end %>
        <% if current_user && current_user.admin %>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user && current_user.admin %>
<%= link_to 'New Post', new_post_path %>
<% end %>
<%= link_to 'Main', root_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>A:</strong>
  <%= @post.a %>
</p>

<p>
  <strong>B:</strong>
  <%= @post.b %>
</p>

<p>
  <strong>C:</strong>
  <%= @post.c %>
</p>

<p>
  <strong>D:</strong>
  <%= @post.d %>
</p>
<% if current_user && current_user.admin %>
<p>
  <strong>TRUE Otvet:</strong>
  <%= @post.otvet %>
</p>
<% end %>
<p>
  <strong>User:</strong>
  <%= @post.user.username %>
</p>
<% if current_user && current_user.admin %>
<%= link_to 'Edit', edit_post_path(@post) %> <% end %>|
<%= link_to 'Back', posts_path %>

<%= render 'comments/comment' %>